name: Generate SVG

on:
  push:
  schedule:
    - cron: "0 */24 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements/requirements.txt

      - run: python scripts/auto_svg_generate.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto generate SVG"